name: treesitter_c
description: Tree-sitter parser for treesitter_c
version: 0.0.1
environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  treesitter:
    git:
      url: https://github.com/oxelf/treesitter-dart

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
